---
title: "Focus Trials"
author: "Bruce Sheng"
date: "`r Sys.Date()`"
output: html_document
---

# FOCUS
```{r gitInstall, eval=FALSE}
# devtools::install_github("gtromano/FOCuS")
```
```{r}
library(FOCuS)
library(ggplot2)
library(scales)
library(readr)

set.seed(42)
databuffer <- c(rnorm(3e5, 1), rnorm(1e4, 0))

f <- function() {
  out <- databuffer[i]     # simulating a pull from a buffer
  i <<- i + 1
  out
}

i <- 1; res <- FOCuS(f, 18)
cutoff = 299875+1
t <- res$t - cutoff; changepoint <- res$changepoint - cutoff

ts_data <- ts(databuffer, start = 1, frequency = 1)
ts_data_250 <- head(tail(ts_data, 10125),250)


plot(ts_data_250, type = 'l')
abline(h = 0)
abline(h = 1)
points(changepoint, ts_data_250[changepoint], col = 'red', pch = 19)
text(changepoint, ts_data_250[changepoint], changepoint, pos = 4)
points(t, ts_data_250[t], col = 'blue', pch = 19)
text(t, ts_data_250[t], t, pos = 4)
```

```{r}
library(FOCuS)
library(ggplot2)
library(scales)
library(readr)

f <- function() {
  out <- databuffer[i]     # simulating a pull from a buffer
  i <<- i + 1
  out
}

databuffer <- c(rnorm(125, 1), rnorm(125, 0), rnorm(125, 3),rnorm(125, -1))
ts_data <- ts(databuffer, start = 1, frequency = 1)
plot(ts_data, type = 'l')

rest <- 500
t = 0
del = 0
while (del<=375) {
  databuffer <- tail(databuffer,rest)
  i <- 1
  res <- FOCuS(f, 18)
  t <- res$t; changepoint <- res$changepoint
  rest <- 500-del
  changepoint = del+changepoint
  points(changepoint, ts_data[changepoint], col = 'red', pch = 19)
  text(changepoint, ts_data[changepoint], changepoint, pos = 4,col = 'red')
  points(del+t, ts_data[del+t], col = 'blue', pch = 19)
  text(del+t, ts_data[del+t], del+t, pos = 4, col = 'blue')
  del = changepoint
}
```

```{r}
library(jsonlite)
library(FOCuS)
library(ggplot2)
library(scales)
library(readr)

f <- function() {
  out <- databuffer[i]     # simulating a pull from a buffer
  i <<- i + 1
  out
}

jsonData <- fromJSON("E:/terms/2nd in 3rd/TSA/project/data/quality_control_3.json")
databuffer <- jsonData$series$raw[[1]]
i <- 1; res <- FOCuS(f, 18)
t <- res$t; changepoint <- res$changepoint
ts_data <- ts(databuffer, start = 1, frequency = 1)
plot(ts_data, type = 'l')
points(changepoint, ts_data[changepoint], col = 'red', pch = 19)
text(changepoint, ts_data[changepoint], changepoint, pos = 4)
points(t, ts_data[t], col = 'blue', pch = 19)
text(t, ts_data[t], t, pos = 4)

```

```{r}
library(FOCuS)
library(ggplot2)
library(scales)
library(readr)
AirQuality <- read.csv("E:/terms/2nd in 3rd/TSA/project/data/AirQualityData.csv")
AirQuality <- na.omit(AirQuality)
NO2 <- AirQuality[,c(1,2)]
NOX <- AirQuality[,c(1,4)]

f <- function() {
  out <- databuffer[i]     # simulating a pull from a buffer
  i <<- i + 1
  out
}

databuffer <- scale(as.vector(NOX[,2]))

ts_data <- ts(databuffer, start = 1, frequency = 1)
plot(ts_data, type = 'l')


all <- nrow(AirQuality)
rest <- all
t = 0
del = 0
while (del<=0.8*all) {
  databuffer <- tail(databuffer,rest)
  i <- 1
  res <- FOCuS(f, 18)
  t <- res$t; changepoint <- res$changepoint
  rest <- all-del
  changepoint = del+changepoint
  points(changepoint, ts_data[changepoint], col = 'red', pch = 19)
  text(changepoint, ts_data[changepoint], changepoint, pos = 4,col = 'red')
  points(del+t, ts_data[del+t], col = 'blue', pch = 19)
  text(del+t, ts_data[del+t], del+t, pos = 4, col = 'blue')
  del = changepoint
}

```

```{r}
library(FOCuS)
library(ggplot2)
library(scales)
library(readr)
hadcet <- read.csv("E:/terms/2nd in 3rd/TSA/project/data/hadcet.csv")
hadcet <- na.omit(hadcet)
mean <- hadcet[,c(1,2)]
max <- hadcet[,c(1,3)]
min <- hadcet[,c(1,4)]

f <- function() {
  out <- databuffer[i]     # simulating a pull from a buffer
  i <<- i + 1
  out
}

databuffer <- scale(as.array(min[,2]))

i <- 1; res <- FOCuS(f, 18)
t <- res$t; changepoint <- res$changepoint
ts_data <- ts(databuffer, start = 1, frequency = 1)
plot(ts_data, type = 'l')
points(changepoint, ts_data[changepoint], col = 'red', pch = 19)
text(changepoint, ts_data[changepoint], changepoint+1877, pos = 4)
points(t, ts_data[t], col = 'blue', pch = 19)
text(t, ts_data[t], t+1877, pos = 4)
```
# wcm.gsa
```{r}
source("E:/terms/2nd in 3rd/TSA/project/related/wcm.gsa-main/main.R")
set.seed(111)
f <- rep(c(0, 5, 2, 8, 1, -2), c(100, 200, 200, 50, 200, 250))
x <- f + arima.sim(list(ar = c(.75, -.5), ma = c(.8, .7, .6, .5, .4, .3)), n = length(f), sd = 1)
res <-wcm.gsa(x)
res

plot(x, type = 'l')
points(res$cp, x[res$cp], col = 'red', pch = 19)
text(res$cp, x[res$cp], res$cp, pos = 4)
title('WCM.GSA(H. Cho and Fryzlewicz,2021)')
```
# TAVC
```{r}
library(mosum)
library(breakfast)
source("E:/terms/2nd in 3rd/TSA/project/related/TAVC.seg-main/main.R")

cpt.sig = c(rep(0,200),rep(2,300),rep(4,200),rep(2,300))

set.seed(123)

x = cpt.sig + arima.sim(model = list(ar = 0.5), sd = sqrt(1-0.5^2), n = 1000)

x.m.c = mosum.tavc(x,G = c(30,60,90,150), alpha = 0.05)
x.m.c$cpts
plot(x, type = 'l')
points(x.m.c$cpts, x[x.m.c$cpts], col = 'red', pch = 19)
text(x.m.c$cpts, x[x.m.c$cpts], x.m.c$cpts, pos = 4)
title('MoSum.TAVC(E. T. McGonigle and H. Cho,2022)')

x.w.c = wbs2.tavc(x, min.int.len = 60)
x.w.c$cpts
plot(x, type = 'l')
points(x.w.c$cpts, x[x.w.c$cpts], col = 'red', pch = 19)
text(x.w.c$cpts, x[x.w.c$cpts], x.w.c$cpts, pos = 4)
title('WBS2(Fryzlewicz,2020)')

```

# 
```{r}

```









```{r}
# remotes::install_github("johnmackintosh/cusumcharter")
```

```{r}
library(cusumcharter)

test_vec <- c(rnorm(25, 0), rnorm(25, 1))
controls <- cusum_control(test_vec, target = 0)

cusum_control_plot(controls, 
                   xvar = obs, 
                   title_text = "CUSUM out of control")
```


